### ISSUE TITLE
Xiaomi remote climate not work after v80.0 update

### ISSUE THREAD

**Issue by vietdht** [Anonym-tsk/home-assistant-components#5]
Please help to check, I have this error after update to HA 0.80
AttributeError: module 'homeassistant.components.remote' has no attribute 'send_command'

**Comment by vietdht** [comment]
`@bind_hass
def send_command(hass, command, entity_id=None, device=None,
                 num_repeats=None, delay_secs=None)`
has been remote from /remote/___init.py___
So I try to add it again and it works, don't know if there is any official fix?

**Comment by thundergreen** [comment]
@vietdht where di u change this? Which file. Mine is also broken after updating to 0.80.0

**Comment by vietdht** [comment]
I installed HA on raspian, for me, it located at `/srv/homeassistant/lib/python3.5/site-packages/homeassistant/components/remote/__init__.py`
you can add below code at line 71
`@bind_hass
def send_command(hass, command, entity_id=None, device=None,
                 num_repeats=None, delay_secs=None):
    """Send a command to a device."""
    data = {ATTR_COMMAND: command}
    if entity_id:
        data[ATTR_ENTITY_ID] = entity_id

    if device:
        data[ATTR_DEVICE] = device

    if num_repeats:
        data[ATTR_NUM_REPEATS] = num_repeats

    if delay_secs:
        data[ATTR_DELAY_SECS] = delay_secs

    hass.services.call(DOMAIN, SERVICE_SEND_COMMAND, data)`

**Comment by thundergreen** [comment]
Not sure if this component has been fixed with latest commits? Could the author please give a Statement ;) I need it urgently as I will get another nice feature in a further Beta 0.80.x  fir this I need this running as well ;)

**Comment by vietdht** [comment]
@thundergreen latest commit seems not work for me, it's broken at init steps.
Keep using my alternative solution :( with 0.80.1

**Comment by thundergreen** [comment]
Thanks reporting back. I'm wondering why the author doesn't take a word here ?

**Comment by thundergreen** [comment]
@vietdht Custom component broke again with latest release 0.84.1. I will not upgrade as I need this component urgently. DO you have an idea whats going on this time? Using the workaround doesn'T seem to work anymore.

Cheers

**Comment by Anonym-tsk** [comment]
@vietdht Please update component from github and try again. It should work.
